# Generated by Django 5.0.1 on 2025-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_sid", models.CharField(max_length=100, unique=True)),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("duration", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
