# Generated by Django 5.0.1 on 2025-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event", models.CharField(max_length=50)),
                ("response_text", models.TextField(blank=True, null=True)),
                ("audio_length", models.FloatField(blank=True, null=True)),
                ("twilio_sid", models.CharField(blank=True, max_length=64, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
